[theme]
base="light"
primaryColor="#0072CE"
backgroundColor="#ffffff"
secondaryBackgroundColor="#e8eef9"
textColor="#000000"
font="sans serif"
[client]
showErrorDetails = false #this is to remove the cache error from showing - take this out when debugging